### ISSUE TITLE
Describe workflow

### ISSUE THREAD

**Issue by ionelmc** [Deepwalker/pundler#1]
Would be nice to see how an usual development workflow would look with pundle (as well as some explanations about each pundle command's intended purposes)

**Comment by Deepwalker** [comment]
Is current readme explain workflow?

**Comment by ionelmc** [comment]
Almost.

Where is the state of the pundle stored? The CWD?

How does the usercustomize.py decide what distributions to activate? (eg: where does it get the distribution set from)

**Comment by Deepwalker** [comment]
Added information about how pundle decide what packages activate.
