### ISSUE TITLE
Support for standalone python executables

### ISSUE THREAD

**Issue by bpiwowar** [Deepwalker/pundler#15]
I would like to be able to have standalone python executable files relying on pundle. The idea would be to be able to start them directly - pundle would take care of downloading/installing dependencies and set the Python path accordingly. 

I am unsure how this could be achieved, but if we agree on a specification for this can be found I can start to work on it.

A first solution would be to create a new command, e.g. `standalone` and add embed the requirements in the standalone file

```
#!/usr/bin/env pundle standalone

# requirements
# icolor
# ...
# /requirements
```

Pundle could then use a special cache to store the frozen state instead of storing it in the same directory to avoid clashes.

**Comment by Deepwalker** [comment]
You need not store requirements.txt, just frozen.txt entries in list for example
And with small function, similar to pundle's internal one, you can install all your dependencies where you need to. As I understand to some folder, that you can "mount" to sys.path then.

Pundle in current state mostly for development step. For production usage pundle provide frozen.txt with pinned versions, that you can install in preferred way (virtualenv or something like that).

But we can make something about bundling - like platter from mitsuhiko. Maybe we can build platter enabled bundles.

If you will provide detailed requirements, we can figure out best way to do job.

**Comment by bpiwowar** [comment]
My intent was more to use pundle for small scripts I wrote, for which I don't want to remember all the dependencies (e.g. when I run them on another computer).

Maybe a way to go would be to programmatically call pundle like e.g.

```
import pundle
pundle.activate("""
icolor
...
""")
```

**Comment by Deepwalker** [comment]
BTW yes, you can use pundle.use('') now. So I think we can close this issue.
https://github.com/Deepwalker/pundler#python-shell-usage

**Comment by bpiwowar** [comment]
great, thanks!
