### ISSUE TITLE
`pundle exec` should be similar to `bundle exec`

### ISSUE THREAD

**Issue by dan-passaro** [Deepwalker/pundler#18]
If I have a requirements.txt with requests in it and try to do

```
$ python -m pundle exec python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
```

it doesn't work. I see that `pundle env` does this, but why use a different command? Since pundler's meant to be a bundler clone, shouldn't `pundle exec` work similarly to `bundle exec`?

In bundler, if I have a Gemfile with sinatra in it, I can do

```
$ bundle exec ruby hello.rb
```

To run the app

Let me know if you think this makes sense, I may be able to contribute a PR

**Comment by Deepwalker** [comment]
`pundle env` command is more descriptive on what it does — augment env with custom PYTHON_PATH.
`pundle exec` starts package scripts.
If you need console, try `pundle console` or `pundle console (ipython|bpython|ptpython)`.

I'm not sure if we need to imitate bundler behaviour.
