### ISSUE TITLE
Support for .pth files?

### ISSUE THREAD

**Issue by ionelmc** [Deepwalker/pundler#2]
Briefly looking over the code, looks like you're using `pkg_resources.Distribution.activate` to add packages to sys.path. Wouldn't that break packages that rely on `.pth` files to be run when site.py run run (excluding the `.pth` that are generated by setuptools for namespace packages)?

Few examples of such packages:
- https://github.com/xando/subprocess.run/blob/master/subprocess.run.pth
- https://github.com/schlamar/pytest-cov/blob/2.0/cov-core/setup.py#L12

Of course it could be argued that those cases are not worth supporting :neckbeard:

**Comment by Deepwalker** [comment]
Mainly I think we just cant fix this cases. Even if pundle will use SourceFileLoader and other importlib mechanics, it cant support site-packages mangling, because have not it.

But both packages easly can be fixed to support pundle.

**Comment by ionelmc** [comment]
Out of curiosity, how can they be fixed?

**Comment by Deepwalker** [comment]
subprocess.run abusing stdlib module - renaming to subprocess_run will fix everything - its just has not a reason to use pth file.

cov-core can have pth file in package directory - it will be loaded by pundle on start.

**Comment by ionelmc** [comment]
> cov-core can have pth file in package directory - it will be loaded by pundle on start.

I don't see any specific handling for this. Is this done by pkg_resources?

**Comment by Deepwalker** [comment]
Ok, its was my mistake - now pundle has not this behaviour.
I will investigate pth files case.

**Comment by Deepwalker** [comment]
I see you have great experience with packaging. How you think, are `pth` files worth supporting? Anyway I cant intercept their creation, and relocate them to the packages folders.

May be we need clean `__load__.py` files per package?
I just don't like what `pth` files are, and this `import` started strings are just hacks. So why hacks?

**Comment by ionelmc** [comment]
I don't really have a strong opinion on them. Not yet :grimacing: 

I was curious to see just how hard would be supporting them.

Python "installs" them via site.py, see: https://hg.python.org/cpython/file/3.4/Lib/site.py#l188 - maybe the `site` module could be used to "fixup" the packages somehow?

About them being hacks, it's hard to say - the whole thing was added 14 years ago: https://hg.python.org/cpython/rev/868d2acf7458?revcount=120

**Comment by Deepwalker** [comment]
About site.py - its not hard to load them manually, but they placed directly to site-packages, and I dont know how to intercept this process without something insane, like chrooting or watching for directory, or other.

**Comment by ionelmc** [comment]
If you could figure out a way to find out who owns the .pth file (iow, if the pth file is owned by an "active" package) then you could call `site.addpackage` only for the active .pth files

**Comment by Deepwalker** [comment]
Have issue with old project with flask-scss that mangle flaskext package through some pth file.
Fixed in https://github.com/Deepwalker/pundler/commit/53f994fe23e7ea1426d342e7d0632ff1b61e756e

Not sure about all packages but in this particular case pth files were copied to package  versioned directory due to `-t` pip option.

**Comment by Deepwalker** [comment]
Sane pth cases are covered. Anything else will need separate issues.
