### ISSUE TITLE
thoughts on vendoring

### ISSUE THREAD

**Issue by dfuentes77** [Deepwalker/pundler#20]
...so that you can vendor packages listed in requirements.txt in the repo itself (~ /vendor) similar to what Bundler, govendor, and many other dependency managers can do.

**Comment by Deepwalker** [comment]
like install packages to the dir instead of secret .pundledir?

**Comment by dfuentes77** [comment]
yes, vendor into our repo

**Comment by Deepwalker** [comment]
`pundle linkall`
