### ISSUE TITLE
Does pandler handler nested VCS references?

### ISSUE THREAD

**Issue by suzukimilanpaak** [Deepwalker/pundler#28]
I have three different projects in my private VCS(bitbucket), which have nested dependencies like the following. Also, Let's say project A, B and C depend on the same pypi lib but different versions.

A => B => C

I'd like to have whole dependencies of all the projects, listed in frozen.txt of project A, and find any conflicts among dependent pypi libs of them. Would it be possible to handle this with the current version of Pundler? thanks

**Comment by Deepwalker** [comment]
So, it is in `install_requires` field, yes? I did not try it, but what I can see from code it should work. Not sure about this, need to create test projects.

**Comment by Deepwalker** [comment]
It should have form like `git@repo`.

**Comment by suzukimilanpaak** [comment]
> install_requires field, yes?

My setup.py looks like this.

setup.py

```
setup(
    ....
    dependency_links=[
        'git+ssh://git@bitbucket.org/szkmp/foo.git@master#egg=foo',
    ],
    install_requires=[
        'foo'
    ]
)
```

Sorry I flowed from Ruby and am new in python. 

Okay, good to hear that. I will let you know if I get any trouble. You could close this issue for now. Thank you
