### ISSUE TITLE
Version of pip package by github ref

### ISSUE THREAD

**Issue by majioa** [Deepwalker/pundler#8]
I need to use the specific version of package referred by github reference id, I used the following record in **requirements.txt**"

```
https://github.com/mitsuhiko/jinja2/archive/85820fceb83569df62fa5e6b9b0f2f76b7c6a3cf.zip
```

But when I use `pundler` I get exception:

```
ValueError: ('Expected version spec in', 'https://github.com/mitsuhiko/jinja2/archive/85820fceb83569df62fa5e6b9b0f2f76b7c6a3cf.zip', 'at', '://github.com/mitsuhiko/jinja2/archive/85820fceb83569df62fa5e6b9b0f2f76b7c6a3cf.zip')
```

The pip's way:

```
-e git+https://github.com/mitsuhiko/jinja2.git@85820fceb83569df62fa5e6b9b0f2f76b7c6a3cf#egg=jinja2-2.8.0
```

also won't work.
How can I do it with `pundler`?

**Comment by Deepwalker** [comment]
Hello. Right now its not possible in pundle. I will think a bit and maybe will release something in day or two.
Average files/urls are not simple to support in pundle philosophy, but I have some idea.
It was in TODO list for too long :)

**Comment by Deepwalker** [comment]
Just added support for pip like string, but without an -e.
Push something like this to requirements.txt:
`git+https://github.com/mitsuhiko/jinja2.git@85820fceb83569df62fa5e6b9b0f2f76b7c6a3cf#egg=jinja2-2.8.0`
